{{- range .Values.models }}
{{- if .enabled }}
{{- if .template }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-template
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "kube-ai-stack.configMapLabels" $ | nindent 4 }}
data:
  template.jinja: |
{{ .template | indent 4 }}
{{- end }}
{{- end }}
{{- end }}