{{- range .Values.models }}
{{- if .enabled }}
---
{{- $merged := mergeOverwrite (deepCopy $.Values.global) . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .name }}-cache"
  namespace: {{ $merged.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $.Values.integrations.argocd.syncWave.pvc }}
  labels:
    {{- include "kube-ai-stack.pvcLabels" $ | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $merged.pvc.storage }}
  storageClassName: {{ $merged.pvc.storageClassName }}
{{- end }}
{{- end }}