{{- range .Values.models }}
{{- if .enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $.Values.integrations.argocd.syncWave.serviceMonitor | quote }}
  labels:
    {{- include "kube-ai-stack.modelLabels" (dict "model" . "root" $) | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kube-ai-stack.modelSelectorLabels" (dict "model" . "root" $) | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 120s
      scrapeTimeout: 120s
{{- end }}
{{- end }}