apiVersion: v2
name: kube-ai-stack
description: A Helm chart for deploying LLM model backends with LiteLLM integration
type: application
version: 0.2.0
appVersion: "1.0.0"
dependencies:
  - name: mlflow
    version: "1.8.1"
    repository: "https://community-charts.github.io/helm-charts"
    condition: global.mlflow.enabled
  - name: phoenix-helm
    version: "5.0.21"
    repository: "oci://registry-1.docker.io/arizephoenix"
    condition: global.phoenix.enabled
